config/routes.rb
CcTally::Application.routes.draw do
  devise_for :users

  resources :scenarios
  resources :factions
  resources :game_types
  resources :players
  resources :games

  root :to => "games#index"
end

app/controllers/factions_controller.rb
class FactionsController < ApplicationController
  # GET /factions
  # GET /factions.xml
  def index
    @factions = Faction.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @factions }
    end
  end

  # GET /factions/1
  # GET /factions/1.xml
  def show
    @faction = Faction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @faction }
    end
  end

  # GET /factions/new
  # GET /factions/new.xml
  def new
    @faction = Faction.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @faction }
    end
  end

  # GET /factions/1/edit
  def edit
    @faction = Faction.find(params[:id])
  end

  # POST /factions
  # POST /factions.xml
  def create
    @faction = Faction.new(params[:faction])

    respond_to do |format|
      if @faction.save
        format.html { redirect_to(@faction, :notice => 'Faction was successfully created.') }
        format.xml  { render :xml => @faction, :status => :created, :location => @faction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @faction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /factions/1
  # PUT /factions/1.xml
  def update
    @faction = Faction.find(params[:id])

    respond_to do |format|
      if @faction.update_attributes(params[:faction])
        format.html { redirect_to(@faction, :notice => 'Faction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @faction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /factions/1
  # DELETE /factions/1.xml
  def destroy
    @faction = Faction.find(params[:id])
    @faction.destroy

    respond_to do |format|
      format.html { redirect_to(factions_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/factions_helper.rb
module FactionsHelper
end

app/views/factions/_form.html.erb
<%= form_for(@faction) do |f| %>
  <% if @faction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faction.errors.count, "error") %> prohibited this faction from being saved:</h2>

      <ul>
      <% @faction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p><%= f.text_field :name %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/factions/edit.html.erb
<h2>Editing faction</h2>

<%= render 'form' %>

<%= link_to 'Show', @faction %> |
<%= link_to 'Back', factions_path %>

app/views/factions/index.html.erb
<h2>Nationality List</h2>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>

<% @factions.each do |faction| %>
  <tr>
    <td><%= faction.name %></td>
    <td><%= link_to 'Edit', edit_faction_path(faction) %></td>
    <td><%= link_to 'Delete', faction, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Faction', new_faction_path %>

app/views/factions/new.html.erb
<h2>New faction</h2>

<%= render 'form' %>

<%= link_to 'Back', factions_path %>

app/views/factions/show.html.erb
<p id="notice"><%= notice %></p>
<h2><%= @faction.name %></h2>
Total Plays: <%= Game.games_with_nationality(@faction).size %><br>

<%= link_to 'Edit', edit_faction_path(@faction) %> |
<%= link_to 'Nationalities List', factions_path %>