config/routes.rb
CcTally::Application.routes.draw do
  devise_for :users

  resources :scenarios
  resources :factions
  resources :game_types
  resources :players
  resources :games

  root :to => "games#index"
end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  default_scope :order => "code ASC"
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  # GET /scenarios
  # GET /scenarios.xml
  def index
    @scenarios = Scenario.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @scenarios }
    end
  end

  # GET /scenarios/1
  # GET /scenarios/1.xml
  def show
    @scenario = Scenario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @scenario }
    end
  end

  # GET /scenarios/new
  # GET /scenarios/new.xml
  def new
    @scenario = Scenario.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @scenario }
    end
  end

  # GET /scenarios/1/edit
  def edit
    @scenario = Scenario.find(params[:id])
  end

  # POST /scenarios
  # POST /scenarios.xml
  def create
    @scenario = Scenario.new(params[:scenario])

    respond_to do |format|
      if @scenario.save
        format.html { redirect_to(@scenario, :notice => 'Scenario was successfully created.') }
        format.xml  { render :xml => @scenario, :status => :created, :location => @scenario }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @scenario.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /scenarios/1
  # PUT /scenarios/1.xml
  def update
    @scenario = Scenario.find(params[:id])

    respond_to do |format|
      if @scenario.update_attributes(params[:scenario])
        format.html { redirect_to(scenarios_url, :notice => 'Scenario was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @scenario.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /scenarios/1
  # DELETE /scenarios/1.xml
  def destroy
    @scenario = Scenario.find(params[:id])
    @scenario.destroy

    respond_to do |format|
      format.html { redirect_to(scenarios_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/views/scenarios/_form.html.erb
<%= form_for(@scenario) do |f| %>
  <% if @scenario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scenario.errors.count, "error") %> prohibited this scenario from being saved:</h2>

      <ul>
      <% @scenario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p><%= f.label :code %>: <%= f.text_field :code %></p>
  <p><%= f.label :name %>: <%= f.text_field :name %></p>
  <p><%= f.label :scenario_date %>: <%= f.date_select :scenario_date, :start_year => 1939, :end_year => 1945 %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scenarios/edit.html.erb
<h2>Editing Scenario</h2>

<%= render 'form' %>

<%= link_to 'Show', @scenario %> |
<%= link_to 'Back', scenarios_path %>

app/views/scenarios/index.html.erb
<h2>Scenario List</h2>

<%= link_to 'New Scenario', new_scenario_path %>
<table>
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th>Date</th>
    <th></th>
    <th></th>
  </tr>

<% @scenarios.each do |scenario| %>
  <tr>
    <td><%= scenario.code %></td>
    <td><%= scenario.name %></td>
    <td><%= scenario.scenario_date.strftime("%d-%b-%Y") unless scenario.scenario_date.nil? %></td>
    <td><%= link_to 'Edit', edit_scenario_path(scenario) %></td>
    <td><%= link_to 'Destroy', scenario, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Scenario', new_scenario_path %>

app/views/scenarios/new.html.erb
<h2>New Scenario</h2>

<%= render 'form' %>

<%= link_to 'Back', scenarios_path %>

app/views/scenarios/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_scenario_path(@scenario) %> |
<%= link_to 'Back', scenarios_path %>