config/routes.rb
CcTally::Application.routes.draw do
  devise_for :users

  resources :scenarios
  resources :factions
  resources :game_types
  resources :players
  resources :games

  root :to => "games#index"
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="usf-8" />
  <meta charset="utf-8" />
  <title>CC Tally</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
</head>
<body>
<div id="wrapper"><!-- #wrapper -->

  <nav><!-- top nav -->
    <div class="menu">
      <ul>
        <li><%= link_to "Home", '/' %></li>
        <li><%= link_to "Players", players_url %></li>
        <li><%= link_to "Scenarios", scenarios_url %></li>
        <li><%= link_to "Nationalities", factions_url %></li>
        <li><%= link_to "Games", game_types_url %></li>
      </ul>
    </div>
  </nav><!-- end of top nav -->

  <header><h1><%= link_to "CC Tally", '/' %></h1></header>

  <section id="main"><!-- #main content and sidebar area -->
  <section id="content"><!-- #content -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </section><!-- end of #content -->

    <aside id="sidebar"><!-- sidebar -->
      <h3>Players</h3>
      <ul>
      <% Player.all.each do |player| %>
        <li><%= link_to player.first_name, player_url(player) %></li>
      <% end %>
      </ul>

      <h3>Nationalities</h3>
      <ul>
      <% Faction.all.each do |faction| %>
        <li><%= link_to faction.name, faction_url(faction) %></li>
      <% end %>
      </ul>

    </aside><!-- end of sidebar -->

  </section><!-- end of #main content and sidebar-->

  <footer>
    <section id="footer-area">

      <section id="footer-outer-block">
        <aside class="footer-segment">
          <h4>BGG Profiles</h4>
          <ul>
	    <% Player.all.each do |p| %>
              <li><%= link_to p.first_name, "http://boardgamegeek.com/user/#{p.handle}" %></li>
            <% end %>
          </ul>
        </aside><!-- end of #first footer segment -->

        <aside class="footer-segment">
          <h4>Top Players</h4>
          <ul>
            <% Game.players_by_wins.each do |player| %>
              <li><%= link_to "#{player.handle} - #{Game.wins_for_player(player)} wins", player_url(player)%></li>
            <% end %>
          </ul>
        </aside><!-- end of #second footer segment -->

        <aside class="footer-segment">
          <h4>Top Scenarios</h4>
          <ul>
            <li><a href="#">one linkylink</a></li>
            <li><a href="#">two linkylinks</a></li>
            <li><a href="#">three linkylinks</a></li>
          </ul>
        </aside><!-- end of #third footer segment -->

        <aside class="footer-segment">
          <h4>What is CC?</h4>
          <p>Combat Commander (CC) is a card-driven board game covering tactical infantry combat in the European Theater of World War II.</p>
        </aside><!-- end of #fourth footer segment -->

      </section><!-- end of footer-outer-block -->

    </section><!-- end of footer-area -->
  </footer>

</div><!-- #wrapper -->
</body>
</html>